#include "config.h" before <stdio.h>
Required with e.g. GCC 4.2.1 because gnulib/lib/stdio.in.h
uses the "restrict" keyword since this gnulib commit:
commit 182afcba2635cbff91240656c7fb3742dd23ab6f
Author: Bruno Haible <bruno@clisp.org>
Date: Sat Feb 22 20:57:30 2020 +0100

Otherwise, the build may die from the declaration of
various printf-like functions with messages like:
./lib/stdio.h:851: error: expected ',' or '...' before 'fp'

fixes https://savannah.gnu.org/bugs/index.php?59276
OK cjwatson@